### ISSUE TITLE
TypeError: extra keyword arguments given

### ISSUE THREAD

**Issue by AdinAck** [adafruit/Adafruit_CircuitPython_SSD1322#2]
Hello! I am trying to use the ssd1322 on my grand central and have wired it up but I am receiving this error:

Traceback (most recent call last):
  File "code.py", line 18, in <module>
  File "adafruit_ssd1322.py", line 92, in __init__
TypeError: extra keyword arguments given

This happens when I run the example program. Also, the display does not display anything.
What does this mean and how can I fix it?
Thanks!

**Comment by AdinAck** [comment]
nevermind, wasn't running circuitpython v5
